openapi: 3.0.0
info:
  title: API TrentoSicura
  description: API to manage TrentoSicura webApp
  version: 1.0.0

servers:
  - url: 'http://localhost:8080'

paths:
  /users/register:
    post:
      summary: Register a new user
      requestBody:
        description: User registration details
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                username:
                  type: string
                password:
                  type: string
              required:
                - email
                - username
                - password
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input or user already exists
        '500':
          description: Server error

  /users/login:
    post:
      summary: Login an existing user
      requestBody:
        description: User login credentials
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Successfully logged in
        '400':
          description: Invalid email or password
        '500':
          description: Server error

  /users/logout:
    post:
      summary: Logout the logged-in user
      responses:
        '200':
          description: Successfully logged out
        '500':
          description: Server error

  /users/delete/{id}:
    delete:
      summary: Delete a user account
      description: Delete the account of the logged-in user.
      parameters:
        - name: id
          in: path
          required: true
          description: The user ID to delete
          schema:
            type: string
      security:
        - jwtAuth: []
      responses:
        '200':
          description: User deleted successfully
        '403':
          description: You cannot delete another user's account
        '404':
          description: User not found
        '500':
          description: Server error

components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    Unauthorized:
      description: Unauthorized access
    NotFound:
      description: Resource not found